"""
This script is used to parse the log file generated by my system.
"""
import re
import json
import os

class LogProcessor:
    def __init__(self, log_file_path, task_mapping_file=None):
        self.log_file_path = log_file_path
        
        # Get the task mapping file path from the configuration file
        config_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'configs/log_config.json')
        try:
            with open(config_path, 'r', encoding='utf-8') as f:
                config = json.load(f)
                default_mapping_file = config.get('task_mapping_file', '')
        except Exception:
            default_mapping_file = ''
        
        self.task_mapping_file = task_mapping_file or default_mapping_file or os.path.join(os.path.dirname(os.path.dirname(__file__)), 'data/Online-Mind2Web/Online_Mind2Web.json')
        self.task_mapping = self._load_task_mapping()

    def _load_task_mapping(self):
        """ Load task mapping file """
        try:
            with open(self.task_mapping_file, 'r', encoding='utf-8') as f:
                return json.load(f)
        except Exception as e:
            print(f"Failed to load the task mapping file: {e}")
            return []

    def _get_task_id_by_task_name(self, task_name):
        """Task ID"""
        if not task_name:
            return ''
            
        for task in self.task_mapping:
            if task.get('confirmed_task') == task_name:
                return task.get('task_id', '')
        return ''

    def parse_log(self):
        """Parse the log file and extract the information"""
        result = {
            "task_id": "",
            "task": "",
            "final_result_response": "",
            "action_history": [],
            "thoughts": []
        }

        try:
            with open(self.log_file_path, 'r', encoding='utf-8') as f:
                content = f.read()
            
            # Finding the task name
            task_patterns = [
                r'The question here is described as "([^"]+)"',
                r'"confirmed_task": "([^"]+)"',
                r'task_name: (.+?)(?:\n|\r\n)',
                r'"task": "([^"]+)"'
            ]
            
            for pattern in task_patterns:
                task_match = re.search(pattern, content)
                if task_match:
                    result["task"] = task_match.group(1).strip()
                    result["task_id"] = self._get_task_id_by_task_name(result["task"])
                    if result["task_id"]:
                        break
            
            # Extract the action field in the last Current trace
            trace_blocks = re.findall(r'Current trace: \{([^}]+)\}', content)
            if trace_blocks:
                last_trace = trace_blocks[-1]
                action_match = re.search(r"'action': '([^']+)'", last_trace)
                if action_match:
                    result["final_result_response"] = action_match.group(1).strip()
            
            # Extract the action_input and action fields from all Planning_Response
            planning_blocks = re.findall(r'Planning_Response:\s*\{([^}]+)\}', content)
            for block in planning_blocks:
                action_input_match = re.search(r'"action_input": "([^"]*)"', block)
                action_match = re.search(r'"action": "([^"]*)"', block)
                
                action_input = action_input_match.group(1) if action_input_match else ""
                action = action_match.group(1) if action_match else ""
                
                if action_input or action:
                    result["action_history"].append(f"{action_input} -> {action}")
            
            # Extract the thought field from all Planning_Response
            for block in planning_blocks:
                thought_match = re.search(r'"thought": "([^"]*)"', block)
                if thought_match:
                    thought = thought_match.group(1).strip()
                    result["thoughts"].append(thought)
            
        except Exception as e:
            print(f"Error parsing log file: {e}")
            
        return result